# Generated by Django 6.0.6 on 2026-06-19 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emails_sent', models.PositiveIntegerField(default=0)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('ran_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-ran_at'],
            },
        ),
        migrations.CreateModel(
            name='SequenceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('delay_days', models.PositiveIntegerField(default=0, help_text='Days after opt-in to send (0 = immediately)')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='HTML allowed. Use {magnet} as a placeholder.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['delay_days', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to='leads.lead')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sends', to='sequences.sequencestep')),
            ],
            options={
                'unique_together': {('lead', 'step')},
            },
        ),
    ]
