# Generated by Django 6.0.6 on 2026-07-07 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('sequences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationrun',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='sentemail',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='sequencestep',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.workspace'),
        ),
    ]
