# Generated by Django 6.0.6 on 2026-07-07 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_emaillist_capturepage_email_list_lead_lists'),
        ('sequences', '0003_alter_automationrun_workspace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencestep',
            name='email_list',
            field=models.ForeignKey(blank=True, help_text='Only send to this list (blank = everyone in the workspace)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='leads.emaillist'),
        ),
    ]
