# Generated by Django 6.0.6 on 2026-06-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('affiliate_url', models.URLField(help_text='Your affiliate/referral link')),
                ('landing_url', models.URLField(blank=True, help_text='Sales/landing page the funnel sends to')),
                ('commission', models.CharField(blank=True, help_text="e.g. '30% recurring'", max_length=100)),
                ('is_recurring', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
