# Generated by Django 6.0.6 on 2026-06-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='checkout_url',
            field=models.URLField(blank=True, help_text='Where buyers pay'),
        ),
        migrations.AddField(
            model_name='offer',
            name='kind',
            field=models.CharField(choices=[('affiliate', 'Affiliate product'), ('own', 'My own product')], default='affiliate', max_length=20),
        ),
        migrations.AddField(
            model_name='offer',
            name='price',
            field=models.CharField(blank=True, help_text="e.g. '$29' or '$29/mo'", max_length=50),
        ),
        migrations.AlterField(
            model_name='offer',
            name='affiliate_url',
            field=models.URLField(blank=True, help_text='Your affiliate/referral link'),
        ),
    ]
