# Generated by Django 6.0.6 on 2026-07-07 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('offers', '0002_offer_checkout_url_offer_kind_offer_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.workspace'),
        ),
    ]
