# Generated by Django 6.0.6 on 2026-07-07 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_backfill_workspaces'),
        ('offers', '0003_offer_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.workspace'),
        ),
    ]
