# Generated by Django 6.0.6 on 2026-07-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_alter_offer_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, help_text='Product image shown in blog CTAs', upload_to='offers/'),
        ),
    ]
