# Generated by Django 6.0.6 on 2026-07-17 20:12

import secrets

import django.db.models.deletion
from django.db import migrations, models


def backfill_public_keys(apps, schema_editor):
    Offer = apps.get_model("offers", "Offer")
    for offer in Offer.objects.filter(public_key=""):
        offer.public_key = secrets.token_urlsafe(24)
        offer.save(update_fields=["public_key"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_workspace_onboarding_step'),
        ('offers', '0005_offer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='access_type',
            field=models.CharField(choices=[('none', 'Link out only'), ('one_time', 'One-time purchase (lifetime access)'), ('subscription', 'Subscription (recurring access)')], default='none', help_text='Native selling: how buyers get access once they pay via Stripe', max_length=20),
        ),
        migrations.AddField(
            model_name='offer',
            name='currency',
            field=models.CharField(default='usd', max_length=3),
        ),
        migrations.AddField(
            model_name='offer',
            name='price_cents',
            field=models.PositiveIntegerField(blank=True, help_text='Native price in the smallest currency unit, e.g. 2900 = $29.00', null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='public_key',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.RunPython(backfill_public_keys, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='offer',
            name='public_key',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='offer',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.CreateModel(
            name='ProductContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('body', models.TextField(blank=True, help_text='Written content shown in the members area (Markdown)')),
                ('file', models.FileField(blank=True, help_text='Downloadable file delivered to buyers', upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='offers.offer')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.workspace')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
