# Generated by Django 6.0.6 on 2026-07-17 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_workspace_onboarding_step'),
        ('offers', '0006_offer_access_type_offer_currency_offer_price_cents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcontent',
            name='drip_days',
            field=models.PositiveIntegerField(default=0, help_text='Days after purchase before this unlocks (0 = right away)'),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='offers.offer')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.workspace')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='productcontent',
            name='module',
            field=models.ForeignKey(blank=True, help_text='Course section this lesson belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='offers.module'),
        ),
    ]
