# Generated by Django 6.0.6 on 2026-07-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_productcontent_drip_days_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcontent',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube, Vimeo or Loom link — plays inline in the members area'),
        ),
    ]
