# Generated by Django 6.0.6 on 2026-07-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_productcontent_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='community_enabled',
            field=models.BooleanField(default=False, help_text='Give buyers a members-only discussion space'),
        ),
    ]
