# Generated by Django 6.0.6 on 2026-07-19 15:11

import apps.offers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0009_offer_community_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcontent',
            name='file',
            field=models.FileField(blank=True, help_text='Downloadable file delivered to buyers', upload_to=apps.offers.models._product_upload_to),
        ),
    ]
