# Generated by Django 6.0.6 on 2026-07-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0010_alter_productcontent_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='freebie_file',
            field=models.FileField(blank=True, help_text="The downloadable file served on the freebie's download page", upload_to='freebies/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='freebie_url',
            field=models.URLField(blank=True, help_text='External link to the freebie (Notion, Drive…), if not a file'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='kind',
            field=models.CharField(choices=[('affiliate', 'Affiliate product'), ('own', 'My own product'), ('freebie', 'Freebie (lead magnet)')], default='affiliate', max_length=20),
        ),
    ]
