# Generated by Django 6.0.6 on 2026-07-16 17:18

from django.db import migrations, models

# Keep in sync with accounts.models.ONBOARDING_STEPS
ONBOARDING_STEPS = 4


def mark_existing_done(apps, schema_editor):
    """Existing workspaces already have content — don't force them through the
    new first-run flow. Only workspaces created after this migration onboard."""
    Workspace = apps.get_model("accounts", "Workspace")
    Workspace.objects.update(onboarding_step=ONBOARDING_STEPS)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_backfill_workspaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='onboarding_step',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RunPython(mark_existing_done, migrations.RunPython.noop),
    ]
