# Generated by Django 6.0.6 on 2026-07-17 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_workspace_onboarding_step'),
        ('offers', '0007_productcontent_drip_days_module_and_more'),
        ('store', '0002_customer_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='offers.productcontent')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='store.customer')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.workspace')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('customer', 'content'), name='uniq_completion_per_lesson')],
            },
        ),
    ]
