# Generated by Django 6.0.6 on 2026-06-27 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0005_video_share_request_id_video_share_results_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('text', 'Text post'), ('image', 'Image'), ('video', 'Video'), ('article', 'Article / blog')], default='text', max_length=12)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True, help_text='Caption for social, or the article body')),
                ('media', models.FileField(blank=True, help_text='Image or video — stored in R2 when configured', upload_to='content/')),
                ('media_url', models.URLField(blank=True, help_text='External media URL (e.g. a rendered video)')),
                ('channels', models.JSONField(blank=True, default=list, help_text='Target channels to publish to')),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='When to publish (blank = now)', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('publishing', 'Publishing'), ('posted', 'Posted'), ('failed', 'Failed')], default='draft', max_length=12)),
                ('share_request_id', models.CharField(blank=True, max_length=120)),
                ('share_results', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_posts', to='videos.video')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
