# Generated by Django 6.0.6 on 2026-07-07 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_backfill_workspaces'),
        ('content', '0004_post_meta_description_post_slug'),
        ('sites', '0001_initial'),
        ('videos', '0007_alter_avatar_workspace_alter_topicidea_workspace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='website',
            field=models.ForeignKey(blank=True, help_text="Which website's blog this article publishes to", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='sites.website'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(condition=models.Q(('website__isnull', False)), fields=('website', 'slug'), name='uniq_article_slug_per_site'),
        ),
    ]
