# Generated by Django 6.0.6 on 2026-07-07 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_post_website_post_uniq_article_slug_per_site'),
        ('videos', '0008_topicidea_archived_video_source_idea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='source_idea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='videos.topicidea'),
        ),
    ]
