# Generated by Django 6.0.6 on 2026-06-18 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('lead_magnet', models.CharField(blank=True, help_text='Freebie they opted in for', max_length=200)),
                ('stage', models.CharField(choices=[('new', 'New'), ('nurturing', 'Nurturing'), ('clicked', 'Clicked offer'), ('converted', 'Converted')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='videos.video')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
