# Generated by Django 6.0.6 on 2026-06-25 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        ('offers', '0002_offer_checkout_url_offer_kind_offer_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapturePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Internal name for this page', max_length=200)),
                ('slug', models.SlugField(help_text='Public URL: /p/<slug>/', unique=True)),
                ('headline', models.CharField(help_text='The big promise at the top', max_length=200)),
                ('subheadline', models.TextField(blank=True, help_text='Supporting line under the headline')),
                ('lead_magnet', models.CharField(help_text='The freebie visitors opt in for', max_length=200)),
                ('button_text', models.CharField(default='Send it to me →', max_length=80)),
                ('success_message', models.CharField(blank=True, help_text='Shown after they opt in (optional)', max_length=300)),
                ('niche', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(blank=True, help_text='Product this page promotes (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capture_pages', to='offers.offer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='source_page',
            field=models.ForeignKey(blank=True, help_text='Which capture page converted them', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.capturepage'),
        ),
    ]
