# Generated by Django 6.0.6 on 2026-06-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_capturepage_lead_source_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('new', 'New'), ('nurturing', 'Nurturing'), ('clicked', 'Clicked product'), ('converted', 'Converted')], default='new', max_length=20),
        ),
    ]
