# Generated by Django 6.0.6 on 2026-07-07 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('leads', '0003_alter_lead_stage'),
        ('videos', '0006_avatar_workspace_topicidea_workspace_video_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturepage',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='lead',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.workspace'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(fields=('workspace', 'email'), name='uniq_lead_email_per_workspace'),
        ),
    ]
