# Generated by Django 6.0.6 on 2026-07-07 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_backfill_workspaces'),
        ('leads', '0004_capturepage_workspace_lead_workspace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturepage',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.workspace'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.workspace'),
        ),
    ]
