# Generated by Django 6.0.6 on 2026-07-07 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_backfill_workspaces'),
        ('leads', '0005_alter_capturepage_workspace_alter_lead_workspace'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.workspace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='capturepage',
            name='email_list',
            field=models.ForeignKey(blank=True, help_text='New signups from this page join this list', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capture_pages', to='leads.emaillist'),
        ),
        migrations.AddField(
            model_name='lead',
            name='lists',
            field=models.ManyToManyField(blank=True, related_name='leads', to='leads.emaillist'),
        ),
    ]
