# Generated by Django 6.0.6 on 2026-07-17 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_workspace_onboarding_step'),
        ('leads', '0007_default_list_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturepage',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='capture/avatars/'),
        ),
        migrations.AddField(
            model_name='capturepage',
            name='layout',
            field=models.CharField(choices=[('capture', 'Email capture (opt-in for a freebie)'), ('sales', 'Sales page (sell a product)'), ('bio', 'Link hub (bio link for your videos)')], default='capture', help_text='What this page is for — picks the public design', max_length=12),
        ),
        migrations.CreateModel(
            name='PageLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='leads.capturepage')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.workspace')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
