# Generated by Django 6.0.6 on 2026-07-21 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_capturepage_avatar_capturepage_layout_pagelink'),
        ('videos', '0015_videofind_video_source_find_videosearch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturepage',
            name='influencer',
            field=models.ForeignKey(blank=True, help_text='Bio pages: the influencer who fronts this link hub', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bio_pages', to='videos.avatar'),
        ),
    ]
