# Generated by Django 6.0.6 on 2026-07-21 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_capturepage_influencer'),
        ('offers', '0011_offer_freebie_file_offer_freebie_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturepage',
            name='freebie',
            field=models.ForeignKey(blank=True, help_text='The freebie (lead magnet) visitors opt in for — delivered on its download page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freebie_captures', to='offers.offer'),
        ),
        migrations.AlterField(
            model_name='capturepage',
            name='offer',
            field=models.ForeignKey(blank=True, help_text='Paid product this page promotes / sells (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capture_pages', to='offers.offer'),
        ),
    ]
