# Generated by Django 6.0.6 on 2026-06-18 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_featured', models.CharField(help_text='The AI tool this video showcases', max_length=200)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('hook', models.CharField(blank=True, max_length=300)),
                ('script', models.TextField(blank=True)),
                ('caption', models.TextField(blank=True, help_text='Post caption + hashtags')),
                ('voice_url', models.URLField(blank=True)),
                ('video_url', models.URLField(blank=True, help_text='Rendered video (fal.ai output)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scripted', 'Script ready'), ('voiced', 'Voiceover ready'), ('rendered', 'Video rendered'), ('approved', 'Approved'), ('posted', 'Posted')], default='draft', max_length=20)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='offers.offer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
