# Generated by Django 6.0.6 on 2026-06-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(help_text='The viral topic/title', max_length=300)),
                ('why_viral', models.TextField(blank=True, help_text='Why this is trending / likely to perform')),
                ('angle', models.TextField(blank=True, help_text='Suggested angle for our AI-tools-for-creators lane')),
                ('selected', models.BooleanField(default=False, help_text='Picked → became a Video')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='video',
            name='source_audio',
            field=models.FileField(blank=True, help_text='Your Portuguese voice memo explaining the idea your way', upload_to='source_audio/'),
        ),
        migrations.AddField(
            model_name='video',
            name='talking_points',
            field=models.TextField(blank=True, help_text='AI-suggested points you could cover on this topic'),
        ),
        migrations.AddField(
            model_name='video',
            name='topic_idea',
            field=models.CharField(blank=True, help_text='The chosen trending topic this video covers', max_length=300),
        ),
        migrations.AddField(
            model_name='video',
            name='transcript_pt',
            field=models.TextField(blank=True, help_text='Transcribed Portuguese from your voice memo'),
        ),
        migrations.AlterField(
            model_name='video',
            name='tool_featured',
            field=models.CharField(blank=True, help_text='The AI tool this video showcases', max_length=200),
        ),
    ]
