# Generated by Django 6.0.6 on 2026-06-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_topicidea_video_source_audio_video_talking_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('appearance', models.TextField(help_text='What the character looks like — used as the image generation prompt')),
                ('style', models.CharField(default='render_3D', help_text='Ideogram style: render_3D, design, realistic, anime, general', max_length=20)),
                ('seed', models.IntegerField(blank=True, help_text='Fixed seed → consistent look across regenerations', null=True)),
                ('image', models.FileField(blank=True, upload_to='character/')),
                ('voice_id', models.CharField(blank=True, help_text='ElevenLabs voice id used to narrate as this character', max_length=120)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
