# Generated by Django 6.0.6 on 2026-06-25 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='avatar',
            field=models.ForeignKey(blank=True, help_text='The character that presents/speaks this video', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='videos.avatar'),
        ),
        migrations.AddField(
            model_name='video',
            name='niche',
            field=models.CharField(blank=True, help_text="Free-form niche/topic for this video's channel (blank = niche-agnostic)", max_length=200),
        ),
        migrations.AlterField(
            model_name='topicidea',
            name='angle',
            field=models.TextField(blank=True, help_text="Suggested angle for the channel's niche"),
        ),
        migrations.AlterField(
            model_name='video',
            name='tool_featured',
            field=models.CharField(blank=True, help_text='The subject/topic this video showcases', max_length=200),
        ),
    ]
