# Generated by Django 6.0.6 on 2026-07-07 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_alter_avatar_workspace_alter_topicidea_workspace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicidea',
            name='archived',
            field=models.BooleanField(default=False, help_text='Hidden from research — cleared out after use'),
        ),
        migrations.AddField(
            model_name='video',
            name='source_idea',
            field=models.ForeignKey(blank=True, help_text='The researched idea this video was spawned from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='videos.topicidea'),
        ),
        migrations.AlterField(
            model_name='topicidea',
            name='selected',
            field=models.BooleanField(default=False, help_text='Legacy: first pick consumed the idea'),
        ),
    ]
