# Generated by Django 6.0.6 on 2026-07-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_topicidea_archived_video_source_idea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicidea',
            name='description',
            field=models.TextField(blank=True, help_text="Plain-English 'what this is' — understand the topic"),
        ),
        migrations.AddField(
            model_name='topicidea',
            name='difficulty',
            field=models.IntegerField(blank=True, help_text='Estimated SEO difficulty 0-100', null=True),
        ),
        migrations.AddField(
            model_name='topicidea',
            name='intent',
            field=models.CharField(blank=True, choices=[('how-to', 'How-to'), ('ideas', 'Ideas'), ('question', 'Question'), ('commercial', 'Commercial'), ('news', 'News')], help_text='Search intent', max_length=20),
        ),
        migrations.AddField(
            model_name='topicidea',
            name='related',
            field=models.JSONField(blank=True, default=list, help_text='Related / rising queries'),
        ),
        migrations.AddField(
            model_name='topicidea',
            name='search_volume',
            field=models.IntegerField(blank=True, help_text='Estimated monthly searches', null=True),
        ),
        migrations.AddField(
            model_name='topicidea',
            name='seed',
            field=models.CharField(blank=True, help_text='The seed term this topic came from (blank = open)', max_length=200),
        ),
        migrations.AddField(
            model_name='topicidea',
            name='trend_dir',
            field=models.CharField(blank=True, choices=[('up', 'Rising'), ('flat', 'Steady'), ('down', 'Cooling')], help_text='Momentum direction', max_length=8),
        ),
        migrations.AddField(
            model_name='topicidea',
            name='trend_pct',
            field=models.IntegerField(blank=True, help_text='Estimated year-over-year interest change (%)', null=True),
        ),
        migrations.AlterField(
            model_name='topicidea',
            name='angle',
            field=models.TextField(blank=True, help_text='Suggested content angle for this topic'),
        ),
        migrations.AlterField(
            model_name='topicidea',
            name='headline',
            field=models.CharField(help_text='The topic / keyword phrase', max_length=300),
        ),
    ]
