# Generated by Django 6.0.6 on 2026-07-09 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_topicidea_description_topicidea_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='voice_ref',
            field=models.FileField(blank=True, help_text='A short, clean clip of the target voice — the F5-TTS cloning reference', upload_to='voice_refs/'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='voice_id',
            field=models.CharField(blank=True, help_text='Legacy ElevenLabs voice id (unused since the F5-TTS swap)', max_length=120),
        ),
        migrations.CreateModel(
            name='VideoSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('text', models.TextField(blank=True, help_text='The spoken phrase for this beat')),
                ('start', models.FloatField(default=0.0, help_text='Start time in the voiceover (seconds)')),
                ('end', models.FloatField(default=0.0, help_text='End time in the voiceover (seconds)')),
                ('image', models.FileField(blank=True, upload_to='video_segments/')),
                ('image_prompt', models.TextField(blank=True, help_text="Art-director prompt used to generate this beat's image")),
                ('uses_avatar', models.BooleanField(default=False, help_text="Whether this beat's image features the avatar character")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='videos.video')),
            ],
            options={
                'ordering': ['video', 'order'],
            },
        ),
    ]
