# Generated by Django 6.0.6 on 2026-07-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_avatar_voice_ref_alter_avatar_voice_id_videosegment'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='gen_status',
            field=models.CharField(blank=True, help_text="'' | running | done | error", max_length=12),
        ),
        migrations.AddField(
            model_name='video',
            name='gen_step',
            field=models.TextField(blank=True, help_text='Human-readable current step (or the error message)'),
        ),
    ]
