# Generated by Django 6.0.6 on 2026-07-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_video_gen_status_video_gen_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='captions',
            field=models.BooleanField(default=True, help_text='Burn phrase-synced captions onto the video (timed to each beat)'),
        ),
    ]
