# Generated by Django 6.0.6 on 2026-07-18 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0012_video_captions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='captions',
            field=models.BooleanField(default=False, help_text='Burn phrase-synced captions onto the video (timed to each beat)'),
        ),
    ]
