# Generated by Django 6.0.6 on 2026-07-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0013_alter_video_captions'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='body_image',
            field=models.FileField(blank=True, help_text='Optional full-body image, used for Motion Clips (dance). Generated from the portrait or uploaded.', upload_to='character/'),
        ),
        migrations.AddField(
            model_name='video',
            name='kind',
            field=models.CharField(choices=[('script', 'Script short'), ('motion', 'Motion clip')], default='script', max_length=12),
        ),
        migrations.AddField(
            model_name='video',
            name='motion_ref',
            field=models.FileField(blank=True, help_text='Reference video whose movement is mapped onto the avatar (Motion clip)', upload_to='motion_refs/'),
        ),
    ]
