# Generated by Django 6.0.6 on 2026-07-21 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_workspace_onboarding_step'),
        ('videos', '0014_avatar_body_image_video_kind_video_motion_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiktok_id', models.CharField(help_text='TikTok video id', max_length=40)),
                ('url', models.URLField(blank=True, help_text='Canonical tiktok.com video URL')),
                ('caption', models.TextField(blank=True, help_text="The video's caption / description")),
                ('author_name', models.CharField(blank=True, max_length=200)),
                ('author_handle', models.CharField(blank=True, max_length=200)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000)),
                ('duration', models.IntegerField(blank=True, help_text='Seconds', null=True)),
                ('music', models.CharField(blank=True, max_length=300)),
                ('views', models.BigIntegerField(default=0)),
                ('likes', models.BigIntegerField(default=0)),
                ('comments', models.BigIntegerField(default=0)),
                ('shares', models.BigIntegerField(default=0)),
                ('saves', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.workspace')),
            ],
            options={
                'ordering': ['-views', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='video',
            name='source_find',
            field=models.ForeignKey(blank=True, help_text='The viral TikTok video this was spawned from (idea or motion clone)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='videos.videofind'),
        ),
        migrations.CreateModel(
            name='VideoSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(blank=True, help_text='The search term (blank = trending feed)', max_length=200)),
                ('status', models.CharField(default='running', help_text='running | done | error', max_length=12)),
                ('error', models.TextField(blank=True, help_text='Failure message when status=error')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='videofind',
            name='search',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finds', to='videos.videosearch'),
        ),
    ]
