# Generated by Django 6.0.6 on 2026-07-07 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_backfill_workspaces'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subdomain', models.SlugField(help_text='Default address: <subdomain>.<app host>', unique=True)),
                ('custom_domain', models.CharField(blank=True, help_text='e.g. sleeptips.co — connected in Phase 1b', max_length=253, null=True, unique=True)),
                ('platform', models.CharField(choices=[('native', 'Native (this app)')], default='native', max_length=20)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('logo', models.ImageField(blank=True, upload_to='sites/logos/')),
                ('accent_color', models.CharField(default='#ff7e2e', max_length=9)),
                ('seo_title_suffix', models.CharField(blank=True, help_text="Appended to page titles, e.g. ' · Sleep Tips'", max_length=120)),
                ('seo_description', models.TextField(blank=True)),
                ('og_image', models.ImageField(blank=True, upload_to='sites/og/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.workspace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL on the site; blank = home page')),
                ('body', models.TextField(blank=True, help_text='Markdown')),
                ('meta_title', models.CharField(blank=True, help_text='Overrides the site default title', max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('is_home', models.BooleanField(default=False)),
                ('nav_order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.workspace')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='sites.website')),
            ],
            options={
                'ordering': ['nav_order', 'title'],
                'constraints': [models.UniqueConstraint(fields=('website', 'slug'), name='uniq_page_slug_per_site')],
            },
        ),
    ]
