# Generated by Django 6.0.6 on 2026-07-07 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_backfill_workspaces'),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('hero', 'Hero'), ('features', 'Features'), ('text', 'Text'), ('cta', 'Call to action'), ('faq', 'FAQ')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='sites.page')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.workspace')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
