# Generated by Django 6.0.6 on 2026-07-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, upload_to='sites/sections/'),
        ),
        migrations.AddField(
            model_name='website',
            name='theme',
            field=models.CharField(choices=[('minimal', 'Minimal'), ('bold', 'Bold'), ('editorial', 'Editorial'), ('warm', 'Warm'), ('tech', 'Tech')], default='minimal', help_text='Visual style — fonts, layout and section styling', max_length=20),
        ),
        migrations.AlterField(
            model_name='section',
            name='kind',
            field=models.CharField(choices=[('hero', 'Hero'), ('features', 'Features'), ('text', 'Text'), ('cta', 'Call to action'), ('faq', 'FAQ'), ('optin', 'Email capture'), ('testimonial', 'Testimonial'), ('stats', 'Stats / social proof'), ('image', 'Image')], max_length=20),
        ),
    ]
