# Generated by Django 6.0.6 on 2026-07-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_section_image_website_theme_alter_section_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='last_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='public_key',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
    ]
