# Generated by Django 6.0.6 on 2026-07-08 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_default_list_backfill'),
        ('offers', '0005_offer_image'),
        ('sites', '0004_website_last_published_at_website_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='cta_magnet_button',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='website',
            name='cta_magnet_cover',
            field=models.ImageField(blank=True, upload_to='sites/magnets/'),
        ),
        migrations.AddField(
            model_name='website',
            name='cta_magnet_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='website',
            name='cta_magnet_list',
            field=models.ForeignKey(blank=True, help_text='List captured leads join for this magnet', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='leads.emaillist'),
        ),
        migrations.AddField(
            model_name='website',
            name='cta_magnet_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='website',
            name='cta_mode',
            field=models.CharField(choices=[('newsletter', 'Newsletter signup'), ('offer', 'Product offer'), ('magnet', 'Lead magnet')], default='newsletter', max_length=12),
        ),
        migrations.AddField(
            model_name='website',
            name='cta_offer',
            field=models.ForeignKey(blank=True, help_text="Product shown when CTA mode is 'Product offer'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='offers.offer'),
        ),
    ]
