# Generated by Django 6.0.6 on 2026-07-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_website_cta_magnet_button_website_cta_magnet_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='hero_variant',
            field=models.CharField(choices=[('dark', 'Dark (premium)'), ('split', 'Split (with image)'), ('minimal', 'Minimal (type-forward)')], default='dark', max_length=12),
        ),
    ]
