# Generated by Django 6.0.6 on 2026-07-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_website_hero_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='card_variant',
            field=models.CharField(choices=[('imagetop', 'Image on top'), ('minimal', 'Minimal (no image)'), ('overlay', 'Title over image')], default='imagetop', max_length=12),
        ),
        migrations.AddField(
            model_name='website',
            name='footer_variant',
            field=models.CharField(choices=[('simple', 'Simple bar'), ('columns', 'Columns'), ('cta', 'Big CTA')], default='simple', max_length=12),
        ),
        migrations.AddField(
            model_name='website',
            name='header_variant',
            field=models.CharField(choices=[('centered', 'Centered menu'), ('left', 'Left menu')], default='centered', max_length=12),
        ),
    ]
