"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env
load_dotenv(BASE_DIR / '.env')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    'SECRET_KEY',
    'django-insecure-285dtej9zyimf+qb=71hd=%=^2(ltyb_o=!9r21g2psg+4dlco',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = [h for h in os.getenv('ALLOWED_HOSTS', '').split(',') if h]
if DEBUG:
    # In dev, accept the app host and any site subdomain (e.g. sleeptips.localhost).
    ALLOWED_HOSTS += ['localhost', '127.0.0.1', '.localhost']

# Comma-separated https origins for CSRF, e.g. "https://app.example.com"
CSRF_TRUSTED_ORIGINS = [o for o in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if o]

# Behind Coolify/Caddy (or any reverse proxy) TLS is terminated at the proxy and
# forwarded over HTTP — trust the proxy's protocol header and secure cookies in prod.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # money-worker apps
    'apps.accounts',
    'apps.sites',
    'apps.social',
    'apps.dashboard',
    'apps.offers',
    'apps.videos',
    'apps.leads',
    'apps.sequences',
    'apps.content',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # serve static files in production
    'apps.sites.middleware.SiteMiddleware',  # route public website hosts → site urlconf
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.accounts.middleware.WorkspaceMiddleware',  # resolves request.workspace
    'apps.accounts.middleware.OnboardingMiddleware',  # escorts new users through first-run
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Dev: prevent browser caching so responsive/CSS changes always show on reload.
if DEBUG:
    MIDDLEWARE += ['config.middleware.NoCacheMiddleware']

ROOT_URLCONF = 'config.urls'

# Public websites (apps.sites) live on their own hostnames. SITE_HOST is the base
# that site subdomains hang off (<subdomain>.<SITE_HOST>); the main app answers on
# SITE_HOST itself. Override in production, e.g. SITE_HOST=moneyworker.io
SITE_HOST = os.getenv('SITE_HOST', 'localhost:8000')
SITE_URLCONF = 'config.site_urls'  # urlconf swapped in for requests to a site host
# Public base URL of the control tower — static sites post opt-ins back here.
APP_BASE_URL = os.getenv('APP_BASE_URL', f'http://{SITE_HOST}')
# Where static site exports are written before deploy.
BUILD_ROOT = os.getenv('BUILD_ROOT', str(BASE_DIR / 'builds'))

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Uses Neon (Postgres) when DATABASE_URL is set, else local SQLite for dev.
DATABASE_URL = os.getenv('DATABASE_URL')
if DATABASE_URL:
    from urllib.parse import urlparse, parse_qs

    _u = urlparse(DATABASE_URL)
    # Neon requires SSL. Honour an explicit ?sslmode=... in the URL, else default
    # to 'require'.
    _sslmode = parse_qs(_u.query).get('sslmode', ['require'])[0]
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': _u.path.lstrip('/'),
            'USER': _u.username,
            'PASSWORD': _u.password,
            'HOST': _u.hostname,
            'PORT': _u.port or 5432,
            'OPTIONS': {'sslmode': _sslmode},
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media (generated voiceovers, rendered videos, images, etc.)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ---------------------------------------------------------------------------
# Media storage — Cloudflare R2 (S3-compatible) when configured, else local disk.
# R2 gives durable public URLs (for Upload-Post, the blog and the calendar) and
# charges nothing for egress. Leave the R2_* vars blank to use local files in dev.
# ---------------------------------------------------------------------------
R2_ACCOUNT_ID = os.getenv('R2_ACCOUNT_ID', '')
R2_ACCESS_KEY_ID = os.getenv('R2_ACCESS_KEY_ID', '')
R2_SECRET_ACCESS_KEY = os.getenv('R2_SECRET_ACCESS_KEY', '')
R2_BUCKET = os.getenv('R2_BUCKET', '')
# Public base URL of the bucket — a custom domain or the pub-xxx.r2.dev URL.
R2_PUBLIC_URL = os.getenv('R2_PUBLIC_URL', '')

USE_R2 = all([R2_ACCOUNT_ID, R2_ACCESS_KEY_ID, R2_SECRET_ACCESS_KEY, R2_BUCKET])

# WhiteNoise's hashed/compressed storage needs a built manifest (collectstatic),
# which dev's runserver doesn't have — so only use it in production.
_STATIC_BACKEND = (
    'django.contrib.staticfiles.storage.StaticFilesStorage' if DEBUG
    else 'whitenoise.storage.CompressedManifestStaticFilesStorage'
)

if USE_R2:
    _DEFAULT_STORAGE = {
        'BACKEND': 'storages.backends.s3.S3Storage',
        'OPTIONS': {
            'bucket_name': R2_BUCKET,
            'endpoint_url': f'https://{R2_ACCOUNT_ID}.r2.cloudflarestorage.com',
            'access_key': R2_ACCESS_KEY_ID,
            'secret_key': R2_SECRET_ACCESS_KEY,
            'region_name': 'auto',
            'signature_version': 's3v4',
            'default_acl': None,        # R2 has no ACLs; bucket is made public in the dashboard
            'querystring_auth': False,  # serve clean, unsigned public URLs
            'file_overwrite': False,
            # Strip the scheme so .url() yields https://<host>/<key>
            'custom_domain': R2_PUBLIC_URL.split('://', 1)[-1].rstrip('/') or False,
        },
    }
else:
    _DEFAULT_STORAGE = {'BACKEND': 'django.core.files.storage.FileSystemStorage'}

STORAGES = {
    'default': _DEFAULT_STORAGE,
    'staticfiles': {'BACKEND': _STATIC_BACKEND},
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login / redirects
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = 'login'

# ---------------------------------------------------------------------------
# Third-party API keys (set these in .env — never commit real keys)
# ---------------------------------------------------------------------------
OPENROUTER_API_KEY = os.getenv('OPENROUTER_API_KEY', '')
OPENROUTER_MODEL = os.getenv('OPENROUTER_MODEL', 'anthropic/claude-opus-4-8')
FAL_API_KEY = os.getenv('FAL_API_KEY', '')  # images, speech-to-text, and F5-TTS voice
RESEND_API_KEY = os.getenv('RESEND_API_KEY', '')
RESEND_FROM_EMAIL = os.getenv('RESEND_FROM_EMAIL', '')

# Email backend for Django's built-in mail (password reset, etc.). When Resend
# is configured we route through it (same key as the rest of the app); otherwise
# fall back to printing emails to the console so local dev still works.
if RESEND_API_KEY and RESEND_FROM_EMAIL:
    EMAIL_BACKEND = 'apps.accounts.email_backend.ResendEmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = RESEND_FROM_EMAIL or 'noreply@getpostforge.cloud'

# Upload-Post — one API to publish a rendered video to YouTube/TikTok/Instagram.
# UPLOAD_POST_USER is the profile name created in the Upload-Post dashboard.
UPLOAD_POST_API_KEY = os.getenv('UPLOAD_POST_API_KEY', '')
UPLOAD_POST_USER = os.getenv('UPLOAD_POST_USER', '')
