# Generated by Django 6.0.6 on 2026-07-07 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_backfill_workspaces'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('x', 'X'), ('pinterest', 'Pinterest')], max_length=20)),
                ('handle', models.CharField(help_text='e.g. @sleeptips', max_length=120)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('up_profile', models.CharField(help_text='Upload-Post profile this account posts through', max_length=120)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Not connected'), ('error', 'Error')], default='disconnected', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.workspace')),
            ],
            options={
                'ordering': ['platform', 'handle'],
            },
        ),
    ]
